### ISSUE TITLE
White icons needed for Dark Mode in Macos Mojave

### ISSUE THREAD

**Issue by sepulworld** [BillCacy/NPOD#3]
Hi Bill! Love this app. My desktop image always feels on point :)

I use Macos Mojave's Dark Mode. In this mode the black colored NPOD icon doesn't show up in the menu bar. It looks like we need a set of "white" NPOD icons that can be used when 'Dark Mode' is enabled: https://www.macworld.co.uk/how-to/mac/dark-mode-mac-3670701/

Let me know what you think. If you want me to try to make a PR to get this working let me know.

**Comment by bruffridge** [comment]
If you want to work on it that would be great. I haven't gotten upgraded to Mojave yet, so it will probably be awhile before I can add support for Dark Mode.

**Comment by sepulworld** [comment]
https://developer.apple.com/documentation/appkit/supporting_dark_mode_in_your_interface
